export enum RepoNames {
    AutoFindReplace ="AutoFindReplace",
    //BadgesPlayground="Badges-playground",
    DotNetFlags = "DotNetFlags",
    FilesForEveryExtensionCreator="FilesForEveryExtensionCreator",
    HelloWorldVstsExtension="HelloWorldVstsExtension",
    OpenInAppLauncher="OpenInApp.Launcher",
    QuickLaunchButtons="QuickLaunchButtons",
    QuizLauncher="Quiz.Launcher",
    SolutionOpenPopUp="SolutionOpenPopUp",
    TrivialApisForIDE="TrivialApisForIDE",
    VisualStudioMarketplaceMetrics   ="VisualStudioMarketplaceMetrics",
    VsixFootie   ="VsixFootie",
    VsixHelloWorldCommandButton    ="VsixHelloWorldCommandButton",
    VsixHelloWorldPopUp   ="VsixHelloWorldPopUp",
    VsixHelloWorldToolBar ="VsixHelloWorldToolBar",
    VsixRatingChaser    ="VsixRatingChaser",
    VsixToolWindowAsyncPackageExample ="VsixToolWindowAsyncPackageExample",
    VsixTwitterWidget   ="VsixTwitterWidget",
    VstsDashboardWidgetProjectTemplate  ="VstsDashboardWidgetProjectTemplate",
    WpfAsyncBindingPropertyExample   ="WpfAsyncBindingPropertyExample",
}
