export enum GroupedBadgeType {
    AppveyorBuildStatus,
    AppveyorUnitTests,
    AzurePipelineBuildStatus,
    BetterCodeHubCompliance,
    Codacy,
    CodeBeat,
    CodeFactor,
    GitHubIssues,
    GitHubPullRequests,
    InspecodeReport,
    InspecodeStatus,
    LgtmAlert,
    LgtmCodeQuality,
    SonarBugs,
    SonarCodeSmells,
    SonarCoverage,
    SonarDuplicatedLinesDensity,
    SonarMaintainability,
    SonarNumberOfLinesOfCode,
    SonarQualityGateStatus,
    SonarReliabilityRating,
    SonarSecurityRating,
    SonarTechnicalDebt,
    SonarVulnerabilities,
}

